list_receipt_text = "Всі рецепти"
receipt_short_text = '<b>{name}</b> {raking}⭐\nпринцип приготування: {main_cooking_principe}\nкатегорія: {category_name}'
receipt_short_text_with_description = '<b>{name}</b> {raking}⭐\nпринцип приготування: {main_cooking_principe}\nкатегорія: {category_name}\n\n{description}'
receipt_create_button_name = 'Додати рецепт'
receipt_detail_title = '<b>{name}</b> {raking}⭐\n Категорія: {category}\n добавлено: {created_at_date}\n час приготування: {estimate_time}\n основне обладнання: {devices}'
receipt_view_button_name = "Подивитися"
receipt_view_button_data = 'receipt_view_receipt_id='
receipt_edit_button_name = '✏️Змінити'
receipt_edit_button_data = 'receipt_edit_receipt_id='
receipt_photo_create_button_name = '📷Добавити'
receipt_photo_create_button_data = 'receipt_photo_receipt_id='
receipt_recalculate_portions_button_name = '🧮порції'
receipt_recalculate_portions_button_data = 'receipt_recalculate_receipt_id='
recalculate_portion_question = 'На скільки порцій перерахувати рецепт?'
recalculate_result_title = 'Базовий рецепт був розрахований на {previous_portions} порцій\nНа {new_portions} порцій рецепт буде виглядати так:'

category_from_receipt_button_name = 'Інші з {category_name}'
categories_list_view_name = 'Категорії'
category__list_view_result_text = 'Список категорій'
category_view_button_name = '{name}: {receipt_count}шт'
category_view_button_data = 'category_id='

comments_list_button_name = '🗒Коментарі'
comments_list_button_data = 'comments_view_receipt_id='
comment_view = '<b>{author}</b> {date} {rate}\n {text}'
comment_create_button_name = '➕комент'
comment_create_button_data = 'comment_create_receipt_id='
