# Generated by Django 4.1.7 on 2023-03-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_telegramuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(default='f', max_length=35),
            preserve_default=False,
        ),
    ]
