# Generated by Django 4.1.7 on 2023-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_telegramuser_first_name_telegramuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(default='', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(default='', max_length=35, null=True),
        ),
    ]
