# Generated by Django 4.1.7 on 2023-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_telegramuser_full_name_alter_telegramuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='type_user',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client')], default='Client', max_length=15),
        ),
    ]
