# Generated by Django 4.1.7 on 2023-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_telegramuser_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='ID юзера в телеграмi.'),
        ),
    ]
