# Generated by Django 4.1.7 on 2023-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(default='', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(default='', max_length=35, null=True),
        ),
    ]
