# Generated by Django 4.1.7 on 2023-02-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import receipt.middlewares


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата створення')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Дата останнього редагування')),
                ('description', models.TextField()),
                ('procedure', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(default=receipt.middlewares.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.category')),
                ('devices', models.ManyToManyField(to='directory.device')),
                ('main_cooking_principe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.cookingtype')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата створення')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Дата останнього редагування')),
                ('rate', models.IntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'normal'), (4, 'good'), (5, 'perfect')])),
                ('author', models.ForeignKey(default=receipt.middlewares.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='culinary.receipt')),
            ],
            options={
                'verbose_name': 'Оцінка рецепту',
                'verbose_name_plural': 'Оцінки рецепту',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.ingredient')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='culinary.receipt')),
                ('user_measurement_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts_components', to='directory.measurementunit')),
            ],
            options={
                'verbose_name': 'Складник рецепту',
                'verbose_name_plural': 'Складники рецепту',
                'ordering': ['receipt'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата створення')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Дата останнього редагування')),
                ('text', models.CharField(max_length=300)),
                ('author', models.ForeignKey(default=receipt.middlewares.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinary.receipt')),
            ],
            options={
                'verbose_name': 'Комент',
                'verbose_name_plural': 'Коменти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['name'], name='culinary_re_name_da03d4_idx'),
        ),
    ]
