# Generated by Django 4.1.7 on 2023-03-12 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary', '0005_receipt_source_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата створення')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Дата останнього редагування')),
                ('file_id', models.CharField(max_length=50)),
                ('file_unique_id', models.CharField(max_length=20)),
                ('file_size', models.IntegerField(null=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='culinary.receipt')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
