# Generated by Django 4.1.7 on 2023-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary', '0006_receiptimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptimage',
            name='file_id',
            field=models.CharField(max_length=200),
        ),
    ]
