# Generated by Django 4.1.7 on 2023-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary', '0007_alter_receiptimage_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_portions',
            field=models.IntegerField(default=0),
        ),
    ]
