# Generated by Django 4.1.7 on 2023-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary', '0008_receipt_receipt_portions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_portions',
            field=models.IntegerField(),
        ),
    ]
