# Generated by Django 4.1.7 on 2023-03-25 11:09

from django.db import migrations
from django.db.models import OuterRef, Subquery


def assign_measurement_units(apps, schema_editor):
    ReceiptComponent = apps.get_model('culinary', 'ReceiptComponent')
    Ingredient = apps.get_model('directory', 'Ingredient')

    subquery = Ingredient.objects.filter(id=OuterRef('ingredient_id')).values('default_measurement_unit')
    ReceiptComponent.objects.filter(user_measurement_unit__isnull=True).update(user_measurement_unit=Subquery(subquery))


def reverse_assign(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('culinary', '0009_alter_receipt_receipt_portions'),
    ]

    operations = [
        migrations.RunPython(assign_measurement_units), migrations.RunPython(reverse_assign)
    ]
