# Generated by Django 4.1.7 on 2023-03-25 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary', '0011_rename_user_measurement_unit_receiptcomponent_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_portions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
