# Generated by Django 4.1.7 on 2023-04-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary', '0012_alter_receipt_receipt_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='estimate_time',
            field=models.DurationField(null=True),
        ),
    ]
