# Generated by Django 4.1.7 on 2023-04-02 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('culinary', '0014_alter_receipt_options_alter_receiptcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptcomment',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'ReceiptComment',
                'verbose_name_plural': 'ReceiptComments'
            },
        ),
        migrations.AlterModelOptions(
            name='receiptimage',
            options={'verbose_name': 'ReceiptImage', 'verbose_name_plural': 'ReceiptImages'},
        ),
    ]
