# Generated by Django 4.1.7 on 2023-04-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('culinary', '0015_alter_receiptcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptcomponent',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.CreateModel(
            name='ReceiptSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Name')),
                ('source', models.TextField(default='', verbose_name='Source')),
                ('receipt', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sources',
                    to='culinary.receipt',
                    verbose_name='Receipt'
                )),
            ],
            options={
                'verbose_name': 'ReceiptSource',
                'verbose_name_plural': 'ReceiptSources',
            },
        ),
    ]
