# Generated by Django 4.1.7 on 2023-04-08 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('culinary', '0016_alter_receiptcomponent_amount_receiptsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsource',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='Дата створення',
                verbose_name='Created_at'
                ),
        ),
        migrations.AddField(
            model_name='receiptsource',
            name='modified_at',
            field=models.DateTimeField(
                auto_now=True,
                help_text='Дата останнього редагування',
                verbose_name='Modified_at'
                ),
        ),
    ]
