# Generated by Django 4.1.7 on 2023-04-22 15:23

from django.db import migrations, models

import culinary.models


class Migration(migrations.Migration):
    dependencies = [
        ('culinary', '0020_receipt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=culinary.models.upload_receipt_photo,
                verbose_name='Photo'
            ),
        ),
    ]
