# Generated by Django 4.1.7 on 2023-04-22 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('culinary', '0021_alter_receipt_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiptImage',
        ),
    ]
