# Generated by Django 4.2.1 on 2023-05-13 19:06

import gdstorage.storage
from django.db import migrations, models

import culinary.models


class Migration(migrations.Migration):
    dependencies = [
        ('culinary', '0023_alter_receipt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='photo',
            field=models.FileField(
                blank=True,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to=culinary.models.upload_receipt_photo,
                verbose_name='Photo'
                ),
        ),
    ]
