# Generated by Django 4.1.7 on 2023-04-02 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0002_culinarycategory_parent_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookingtype',
            options={'ordering': ['name'], 'verbose_name': 'CookingType', 'verbose_name_plural': 'CookingTypes'},
        ),
        migrations.AlterModelOptions(
            name='culinarycategory',
            options={
                'ordering': ['name'],
                'verbose_name': 'CulinaryCategory',
                'verbose_name_plural': 'CulinaryCategories'
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='measurementunit',
            options={
                'ordering': ['name'],
                'verbose_name': ('MeasurementUnit',),
                'verbose_name_plural': ('MeasurementUnits',)
            },
        ),
        migrations.AlterField(
            model_name='cookingtype',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='culinarycategory',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='culinarycategory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='culinarycategory',
            name='parent',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='child_categories',
                to='directory.culinarycategory',
                verbose_name='CulinaryCategory'
                ),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(
                choices=[('electric', 'different electric stuff'), ('manual', 'devices for hand use only')],
                max_length=10,
                verbose_name='Device_type'
                ),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='default_measurement_unit',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='directory.measurementunit',
                verbose_name='MeasurementUnit'
                ),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Symbol'),
        ),
    ]
