# Generated by Django 4.1.7 on 2023-04-02 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0003_alter_cookingtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementunit',
            options={
                'ordering': ['name'],
                'verbose_name': 'MeasurementUnit',
                'verbose_name_plural': 'MeasurementUnits'
            },
        ),
    ]
