# Generated by Django 4.1.7 on 2023-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0006_ingredient_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='product_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Product_data'),
        ),
    ]
